version: '3'
services:
  web:
    image: nginx:latest
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./wp-api:/var/www/html/
    links:
        - wordpress
    restart: always
    depends_on: # Uncomment when you are ready for production. end  str 22
      - next

  next:
    build: ./front-end/
    restart: always
    container_name: next_app
    command:
      "npm run start"
    ports:
        - 3000:3000

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    restart: always
    #
    # Save our SSL certs between runs so they aren't regenerated on every single run.
    #
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: '127.0.0.1 -> http://web:80 #local'
      # DOMAINS: 'www.domaine.com => domaine.com, domaine.com -> http://web:80 #production' # Uncomment when you are ready for production.
      #
      # Allow larger files to be uploaded
      #
      CLIENT_MAX_BODY_SIZE: 64M

  mysql:
    image: mariadb
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=t9cqT
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: t9cqT

  wordpress:
    image: wordpress:5.3.0-php7.2-fpm
    ports:
        - '9000:9000'
    volumes:
      - ./wp-api:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
        - WORDPRESS_DB_NAME=admin_wp
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=t9cqTCGxJy
    links:
        - mysql
    restart: always